/** Human-readable labels for common tool names (used in Done! fallback and timeout recovery). */
export const ACTION_LABELS: Record<string, string> = {
  // Reminders
  set_reminder: "Reminder set",
  set_recurring_reminder: "Recurring reminder set",
  cancel_reminder: "Reminder cancelled",
  list_reminders: "Reminders loaded",
  // Email
  schedule_email: "Email scheduled",
  cancel_scheduled_email: "Scheduled email cancelled",
  list_scheduled_emails: "Scheduled emails listed",
  draft_email: "Email drafted",
  gmail_search: "Inbox searched",
  gmail_read: "Email read",
  summarize_recent_emails: "Inbox summarized",
  draft_gmail_reply: "Reply drafted",
  sent_history: "Sent history loaded",
  // Tasks
  add_task: "Task added",
  complete_task: "Task done",
  reopen_task: "Task reopened",
  delete_task: "Task deleted",
  complete_all_open_tasks: "All tasks done",
  delete_all_tasks: "Tasks cleared",
  list_tasks: "Tasks loaded",
  // Calendar
  draft_calendar_event: "Calendar event drafted",
  update_calendar_event: "Event updated",
  delete_calendar_event: "Event deleted",
  list_upcoming_events: "Calendar loaded",
  calendar_today: "Today's calendar",
  calendar_week: "This week's calendar",
  search_events: "Events found",
  calendar_find_free_time: "Free time found",
  // Memory
  remember: "Saved to memory",
  forget_memory: "Memory removed",
  clear_all_memories: "Memories cleared",
  list_memories: "Memories listed",
  search_archived_memory: "Archive searched",
  list_archived_memory: "Archive listed",
  // Settings
  set_timezone: "Timezone updated",
  set_location: "Location updated",
  set_language: "Language updated",
  enable_morning_briefing: "Morning briefing enabled",
  disable_morning_briefing: "Morning briefing disabled",
  enable_evening_summary: "Evening summary enabled",
  disable_evening_summary: "Evening summary disabled",
  enable_pre_meeting_reminders: "Pre-meeting reminders enabled",
  disable_pre_meeting_reminders: "Pre-meeting reminders disabled",
  enable_briefing_emails: "Briefing emails enabled",
  disable_briefing_emails: "Briefing emails disabled",
  get_my_settings: "Settings loaded",
  // Search & finance
  web_search: "Web search",
  news_search: "News loaded",
  weather: "Weather loaded",
  stock_price: "Stock price loaded",
  stock_history: "Stock history loaded",
  crypto_price: "Crypto price loaded",
  fx_rate: "Exchange rate loaded",
  // Drive
  drive_search: "Drive searched",
  drive_list_recent: "Recent Drive files listed",
  drive_get_link: "Drive link fetched",
  drive_read_text: "Drive file read",
  drive_upload_recent_media: "File uploaded to Drive",
  // Media AI
  ocr_image: "Image read",
  summarize_image: "Image summarized",
  read_document: "Document read",
  summarize_document: "Document summarized",
  transcribe_audio: "Audio transcribed",
  summarize_audio: "Audio summarized",
  // Receipts
  scan_receipt: "Receipt scanned",
  list_receipts: "Receipts listed",
  search_receipts: "Receipts searched",
  delete_receipt: "Receipt deleted",
  // Lists
  show_all_lists: "Lists shown",
  list_items: "List loaded",
  add_to_list: "Added to list",
  remove_from_list: "Removed from list",
  clear_list: "List cleared",
  delete_list: "List deleted",
  // Contacts & places
  contacts_search: "Contacts found",
  suggest_places: "Places found",
  // Google accounts
  list_google_accounts: "Accounts listed",
  connect_google_account: "Connect link sent",
  switch_google_account: "Account switched",
  disconnect_google_account: "Account disconnected",
  // Misc
  show_help: "Help shown",
  export_my_data: "Data exported",
  get_morning_briefing: "Briefing ready",
  get_evening_summary: "Summary ready",
};
