/** Human-readable labels for common tool names (used in Done! fallback and timeout recovery). */
export const ACTION_LABELS: Record<string, string> = {
  set_reminder: "Reminder set",
  set_recurring_reminder: "Recurring reminder set",
  cancel_reminder: "Reminder cancelled",
  schedule_email: "Email scheduled",
  cancel_scheduled_email: "Scheduled email cancelled",
  add_task: "Task added",
  complete_task: "Task done",
  delete_task: "Task deleted",
  remember: "Saved to memory",
  forget_memory: "Memory removed",
  clear_all_memories: "Memories cleared",
  draft_calendar_event: "Calendar event drafted",
  set_timezone: "Timezone updated",
  set_location: "Location updated",
  set_language: "Language updated",
  enable_morning_briefing: "Morning briefing enabled",
  disable_morning_briefing: "Morning briefing disabled",
  enable_evening_summary: "Evening summary enabled",
  disable_evening_summary: "Evening summary disabled",
  web_search: "Web search",
  stock_history: "Stock history loaded",
  drive_search: "Drive searched",
  drive_list_recent: "Recent Drive files listed",
  drive_get_link: "Drive link fetched",
  drive_read_text: "Drive file read",
  list_receipts: "Receipts listed",
  search_receipts: "Receipts searched",
  scan_receipt: "Receipt scanned",
  list_memories: "Memories listed",
  search_archived_memory: "Archive searched",
  list_archived_memory: "Archive listed",
  sent_history: "Sent history loaded",
  calendar_find_free_time: "Free time found",
  show_all_lists: "Lists shown",
  list_scheduled_emails: "Scheduled emails listed",
  ocr_image: "Image read",
  summarize_image: "Image summarized",
  read_document: "Document read",
  summarize_document: "Document summarized",
};
